CI: Update build script for Ubuntu to require Ubuntu 24.04
Also defaults to Qt6 and x86_64 builds, thus no toolchain file is
needed and no additional data in buildspec is needed either.

diff --git a/.github/scripts/utils.zsh/check_ubuntu b/.github/scripts/utils.zsh/check_ubuntu
--- a/.github/scripts/utils.zsh/check_ubuntu
+++ b/.github/scripts/utils.zsh/check_ubuntu
@@ -13,6 +13,12 @@ if [[ -f /etc/os-release ]] {
     log_group
     return 2
   }
+
+  autoload -Uz is-at-least && if ! is-at-least 24.04 ${dist_version}; then
+    log_error "Not running on a recent-enough Ubuntu distribution. Aborting"
+    log_group
+    return 2
+  fi
 } else {
   log_error "Unable to determine local Linux distribution, but Ubuntu is required. Aborting"
   log_group
