CI: Update Flatpak AppStream validation
Also add AppStream validation to Build Project workflow

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -49,7 +49,7 @@ jobs:
       run:
         shell: bash
     env:
-      FLATPAK_BUILD_PATH: flatpak_app/files/share
+      FLATPAK_BUILD_SHARE_PATH: flatpak_app/files/share
       TWITCH_CLIENTID: ${{ secrets.TWITCH_CLIENT_ID }}
       TWITCH_HASH: ${{ secrets.TWITCH_HASH }}
       RESTREAM_CLIENTID: ${{ secrets.RESTREAM_CLIENTID }}
@@ -114,17 +114,17 @@ jobs:
           branch: ${{ matrix.branch }}
 
       - name: Validate AppStream
-        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
-        run: |
-          : Validate AppStream
-          appstream-util validate appdata/com.obsproject.Studio.appdata.xml
+        uses: ./.github/actions/flatpak-builder-lint
+        with:
+          artifact: appstream
+          path: ${{ env.FLATPAK_BUILD_SHARE_PATH }}/metainfo/com.obsproject.Studio.metainfo.xml
 
       - name: Verify Icon and Metadata in app-info
-        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
+        working-directory: ${{ env.FLATPAK_BUILD_SHARE_PATH }}
         run: |
           : Verify Icon and Metadata in app-info
-          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "Missing 128x128 icon in app-info!"; exit 1; }
-          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "Missing com.obsproject.Studio.xml.gz in app-info!"; exit 1; }
+          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "::error::Missing 128x128 icon in app-info"; exit 1; }
+          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "::error::Missing com.obsproject.Studio.xml.gz in app-info"; exit 1; }
 
       - name: Validate build directory
         uses: ./.github/actions/flatpak-builder-lint
